name: pytest

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - 3.9
          - 3.8
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dev requirements
        run: |
          pip3 install pytest coverage coveralls
      - name: Install package
        run: |
          pip3 install .
      - name: Pytest
        run: |
          coverage run -m pytest
      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          coveralls
